package com.group.financialcomputing;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import java.util.Map;

/**
 *
 * @author yongzhaohuang
 */
public class StockPWindow extends javax.swing.JFrame {

	// Variables declaration - do not modify
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private Map<String, List<OneDayStock>> stockPortfolio;
	private JPopupMenu jPopupMenu;
	private JMenuItem mCut, mCopy, mPaste, mManageExistingStock, mPickStock, mShowPortfolio, mOptimization;
	// End of variables declaration

	/**
	 * Creates new form StockPWindow
	 */
	public StockPWindow() {
		initComponents();
	}

	public StockPWindow(StockManagementWindow stockManagementWindow) {
		stockPortfolio = stockManagementWindow.getPickedStocks();
		initComponents();
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jPopupMenu = new JPopupMenu();

		mCut = new JMenuItem("Cut");
		jPopupMenu.add(mCut);

		mCopy = new JMenuItem("Copy");
		jPopupMenu.add(mCopy);

		mPaste = new JMenuItem("Paste");
		jPopupMenu.add(mPaste);

		jPopupMenu.addSeparator();

		mManageExistingStock = new JMenuItem("Manage Existing stock");
		jPopupMenu.add(mManageExistingStock);

		mPickStock = new JMenuItem("Pick Stock");
		jPopupMenu.add(mPickStock);

		jPopupMenu.addSeparator();

		mShowPortfolio = new JMenuItem("Show Portfolio Performance");
		jPopupMenu.add(mShowPortfolio);

		mOptimization = new JMenuItem("Optimize Portfolio");
		jPopupMenu.add(mOptimization);

		jTable1.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				if (e.getButton() == MouseEvent.BUTTON3) {
					jPopupMenu.show(e.getComponent(),e.getX(),e.getY());
				}
			}
		});

		mCut.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent actionEvent) {
				System.out.println("hello");
				action(actionEvent);
			}
		});

		mCopy.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent actionEvent) {
				action(actionEvent);
			}
		});

		mPaste.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent actionEvent) {
				action(actionEvent);
			}
		});

		mPickStock.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent actionEvent) {
				action(actionEvent);
			}
		});

		mManageExistingStock.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent actionEvent) {
				action(actionEvent);
			}
		});

		mShowPortfolio.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent actionEvent) {
				action(actionEvent);
			}
		});

		mOptimization.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent actionEvent) {
				action(actionEvent);
			}
		});

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object [][] {
						{1, 2, 3, 4, 5, 6, 7, 8},
						{null, null, null, null, null, null, null, null},
						{null, null, null, null, null, null, null, null},
						{null, null, null, null, null, null, null, null},
						{null, null, null, null, null, null, null, null}
				},
				new String [] {
						"Weight", "Name", "Start Date", "End Date", "Highest", "Lowest", "Return", "Risk"
				}
		));
		jScrollPane1.setViewportView(jTable1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
		);

		pack();
	}

	private void action(ActionEvent e) {
		if (e.getActionCommand().equals(mCopy.getText())) {
		}
		else if (e.getActionCommand().equals((mCut.getText()))) {
		}
		else if (e.getActionCommand().equals((mManageExistingStock.getText()))) {

		}
		else if (e.getActionCommand().equals((mPaste.getText()))) {

		}
		else if (e.getActionCommand().equals(mOptimization.getText())){
			OptimizationWindow optimizationWindow = new OptimizationWindow();
			optimizationWindow.setVisible(true);
		}
	}
}
